### ISSUE TITLE
Demo repo refresh

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Demo.Simple#137]
## Description
As a new user I want to be able to quickly explore the capabilities of the Alkemio platform

## Acceptance criteria

- [ ] Demo quickstart updated to use alkemio images from early June
- [ ] Demo spreadsheet updated to have better images + content
- [ ] Updated documentation to guide the user
- [ ] Make it easy to verify emails / have a way to turn it off for demo? Default account verification?
